# Generated by Django 2.2.6 on 2019-11-09 11:31

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title of post')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title', unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='comment', verbose_name='Picture')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('public_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of publication')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255, null=True, verbose_name='Author of post')),
                ('comment', models.CharField(max_length=255, verbose_name='Text of comment')),
                ('public_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of publication')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Posts', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
            },
        ),
    ]
