# Generated by Django 2.2.6 on 2019-11-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191109_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.CharField(max_length=255, verbose_name='Author of post'),
        ),
    ]
